#include "jcc/ja.h"
#include "jcc/jae.h"
#include "jcc/jb.h"
#include "jcc/jbe.h"
#include "jcc/je.h"
#include "jcc/jg.h"
#include "jcc/jge.h"
#include "jcc/jl.h"
#include "jcc/jle.h"
#include "jcc/jne.h"
#include "jcc/jng.h"
#include "jcc/jnle.h"
#include "jcc/jo.h"
#include "jcc/jno.h"
#include "jcc/js.h"
#include "jcc/jns.h"
#include "jcc/jp.h"
#include "jcc/jpo.h"


